Command = <Leader> ( NewGame
                   | Follow
                   | Ignore
                   | Standings
                   | Rating
                   | Undo
                   | Help
                   | ReleaseNotes
                   ) <any*>
Leader = w* '@'? 'arpad' w* ':'? w*

NewGame = Player <w+ Beat w+> Player
Beat = 'beat' | 'defeated' | 'win' | 'wins'

Follow = <('follow'|'unignore') w+> Player
Ignore = <('ignore'|'unfollow') w+> Player

Standings = (<'standing'>|<'standings'>|<'ratings'>|<'top' w+> num)

Rating = Player <w+ ('rating'|'ratings')>

Undo = <w*'undo'w*>

Help = <w*'help' '!'? w*>

Player = word

ReleaseNotes = <'release notes'>

w = #"\s"
<word> = #"[a-zA-Z0-9\*\+\!\-\_\?]+"
any = #"."
<num> = #"[0-9]+"
